// flow-typed signature: b8155bc86ad4ba63d27eccc9d7ff89f1
// flow-typed version: <<STUB>>/auto-retry_v^1.4.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auto-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auto-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auto-retry/src/index' {
  declare module.exports: any;
}

declare module 'auto-retry/src/index.transpiled' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auto-retry/src/index.js' {
  declare module.exports: $Exports<'auto-retry/src/index'>;
}
declare module 'auto-retry/src/index.transpiled.js' {
  declare module.exports: $Exports<'auto-retry/src/index.transpiled'>;
}
