// flow-typed signature: cafc377aa3ad56ccc34671e722cede6f
// flow-typed version: <<STUB>>/http_v^0.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
