// flow-typed signature: 2f2488808d5c8252adf8fcecd59f096a
// flow-typed version: <<STUB>>/promise-map-limit_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-map-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-map-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'promise-map-limit/index' {
  declare module.exports: $Exports<'promise-map-limit'>;
}
declare module 'promise-map-limit/index.js' {
  declare module.exports: $Exports<'promise-map-limit'>;
}
