// flow-typed signature: a7fbc9f4c9cb6d37123c20ff3624cc19
// flow-typed version: <<STUB>>/retriable-promise_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retriable-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retriable-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retriable-promise/index' {
  declare module.exports: $Exports<'retriable-promise'>;
}
declare module 'retriable-promise/index.js' {
  declare module.exports: $Exports<'retriable-promise'>;
}
