// flow-typed signature: c464ad769bdc325854190e4881ccb20a
// flow-typed version: <<STUB>>/robinhood_v^1.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'robinhood'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'robinhood' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'robinhood/examples/get_quote' {
  declare module.exports: any;
}

declare module 'robinhood/src/robinhood' {
  declare module.exports: any;
}

declare module 'robinhood/test/robinhood' {
  declare module.exports: any;
}

// Filename aliases
declare module 'robinhood/examples/get_quote.js' {
  declare module.exports: $Exports<'robinhood/examples/get_quote'>;
}
declare module 'robinhood/src/robinhood.js' {
  declare module.exports: $Exports<'robinhood/src/robinhood'>;
}
declare module 'robinhood/test/robinhood.js' {
  declare module.exports: $Exports<'robinhood/test/robinhood'>;
}
