// flow-typed signature: 343a1075c8c9f060826a37d392fafa01
// flow-typed version: <<STUB>>/yahoo-stocks_v^2.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yahoo-stocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yahoo-stocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yahoo-stocks/__tests__/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yahoo-stocks/__tests__/index.js' {
  declare module.exports: $Exports<'yahoo-stocks/__tests__/index'>;
}
declare module 'yahoo-stocks/index' {
  declare module.exports: $Exports<'yahoo-stocks'>;
}
declare module 'yahoo-stocks/index.js' {
  declare module.exports: $Exports<'yahoo-stocks'>;
}
