export const userConstants = {
    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
    LOGOUT: "USERS_LOGOUT"
  };
  
  export const actions = {
    BUY_REQUEST: "BUY_REQUEST",
    SELL_REQUEST: "SELL_REQUEST",
    CANCEL_REQUEST: "CANCEL_REQUEST"
  };
  
  export const messages = {
    POSITIONS: "POSITIONS",
    ORDERS: "ORDERS",
    PRICE: "PRICE",
    UPDATE_PRICE: "SERVER/UPDATE_PRICE",
    UPDATE_POSITIONS: "SERVER/UPDATE_POSITIONS",
    UPDATE_ORDERS: "SERVER/UPDATE_ORDERS"
  };
  