export const UPDATE_TIME_INTERVAL = "UPDATE_TIME_INTERVAL";
export const UPDATE_UNDER_BID_PRICE = "UPDATE_UNDER_BID_PRICE";
export const UPDATE_OVER_ASK_PRICE = "UPDATE_OVER_ASK_PRICE";
export const UPDATE_QUANTITY_AUTO = "UPDATE_QUANTITY_AUTO";
export const NUMBER_OF_RUNS = "NUMBER_OF_RUNS";
export const UPDATE_NUMBER_OF_OPEN_ORDERS = "UPDATE_NUMBER_OF_OPEN_ORDERS";
