export const PLACE_BUY_REQUEST = "PLACE_BUY_REQUEST";
export const PLACE_BUY_REQUEST_SUCCESS = "PLACE_BUY_REQUEST_SUCCESS";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const UPDATE_SELL_ORDER_TYPE = "UPDATE_SELL_ORDER_TYPE";
export const UPDATE_BUY_ORDER_TYPE = "UPDATE_BUY_ORDER_TYPE";
export const UPDATE_BUY_PRICE = "UPDATE_BUY_PRICE";
export const UPDATE_SELL_PRICE = "UPDATE_SELL_PRICE";
