export const PLACE_SELL_REQUEST = "PLACE_SELL_REQUEST";
export const PLACE_SELL_REQUEST_SUCCESS = "PLACE_SELL_REQUEST_SUCCESS";
export const UPDATE_SELL_ORDER_TYPE_TYPE = "UPDATE_SELL_ORDER_TYPE_TYPE";
export const UPDATE_SELL_ORDER_PRICE_PRICE = "UPDATE_SELL_ORDER_PRICE_PRICE";
